### ISSUE TITLE
validation_step.. Use of Pickle required?

### ISSUE THREAD

**Issue by theanniemal** [Haley-Kubala/Senior-Design-Project#10]
In an endeavor to save the ID and the timestamp returned by the return_id_and_timestamp function, I tried to implement Pickle using some rudimentary information from Stack Overflow. Alex, you mentioned that i needed to save these variables, but is Pickle the best route to accomplish what you meant when you said to save the variables? Does this get close to what you were thinking when we talked about saving these values?

https://github.com/theanniemal/Senior-Design-Project/blob/master/validation_step

**Comment by ptmmrblack** [comment]
I think you're over thinking this one annie
Your function return_id_and_time returns the id and time but you need assign them to variables so you can call them later on in main.
Pickle is probably over complicating the task.  Also, main should always be the last function, otherwise it wont know about the other functions defined after it.
