### ISSUE TITLE
2 Validation scripts.. Which is closer?

### ISSUE THREAD

**Issue by theanniemal** [Haley-Kubala/Senior-Design-Project#4]
Which validation script would be a better option/which is closer to working? Just tinkered around with some StackOverflow info.

**Comment by ptmmrblack** [comment]
I dont have a way to view your code, you will have to put in a merge request or post a direct link to your fork of the repo

**Comment by theanniemal** [comment]
alright, I put in the merge request. sry >.<

**Comment by ptmmrblack** [comment]
I'm not sure either is very close.  Using the use case cards we created draw out an outline of what the validation script is supposed to do, you should be able to note the functions you need and what you are validating.  there will have to be some things that happen like connect to mongo, and some other things that validate that the input is more than a string, but that the string data isn't garbage.  
I don't think the first script will run, but if it does, enteredID is never defined so it will always fail.  you define the data file as a file but you never open it.  Check with Haley about how she is formatting the data file, and what it will be named, you might have to split the line to actually view the ID.  I do appreciate that the function is returning a boolean.   This code seems to want to check if the entered id matches the ID when the student returns.  you will need a separate function that checks if the id is valid when the student leaves.
The second script takes its data from user input.  This is fine for manual testing, but won't work in the production environment.  using the with constructor to open the file is good, its very safe, and should always be done.  here you are checking if it is a string, but the length of the string is important too.  Ideally you would check if the string contains valid characters (numbers).  this function should also return a boolean as it is a check. 

Both files should end with .py because they are python files.  And you should document your functions at the top to state what you expect them to do.
